### PR TITLE
file_handling_improvement

### PR DESCRIPTION
**Pull request by ThomasEnzinger**
When testing the appmyproduct-device-stub I had the problem, that I could not save data to the fingerprint-memory. The error was thrown from 'rename(tempFilename, filename)' because the destination file was still open.

OS: Windows 8.1, 64 Bit
Visual Studio 2015 Community

### CODE REVIEW

**Comment by mkm85** [comment]
The missing fclose should be added in all occurences of return. A better approach would be splitting the function into a file opening/closing function and a file reading function.

It seems like the remove is unfortunately neccessary on windows.

**Comment by ThomasEnzinger** [comment]
Correct, I should have seen that too. I would suggest splitting ...
should I do this ... or is there a 'code owner' who should do this ? 

Yes, the remove is necessary. First I tried to only put the close, but
it was not sufficient. 

Am 2017-06-21 16:06, schrieb mkm85:

> The missing fclose should be added in all occurences of return. A better approach would be splitting the function into a file opening/closing function and a file reading function. 
> 
> It seems like the remove is unfortunately neccessary on windows. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/nabto/unabto/pull/44#issuecomment-310089295
[2]

**Comment by mkm85** [comment]
If you want to do it it will be great.

**Comment by ThomasEnzinger** [comment]
no problem, I'll do 

Am 2017-06-21 16:38, schrieb mkm85:

> If you want to do it it will be great. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/nabto/unabto/pull/44#issuecomment-310099452
[2]

**Comment by ThomasEnzinger** [comment]
but I can only do it on the weekend. At the moment I do not have access
to my App. 

Am 2017-06-21 16:38, schrieb mkm85:

> If you want to do it it will be great. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/nabto/unabto/pull/44#issuecomment-310099452
[2]

**Pull request closed without merging**
